
services:
  db:
    build: ./db
    container_name: my-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: my-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: 1234
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
